### ISSUE TITLE
Cannot specify warehouse or role when mounting Snowflake

### ISSUE THREAD

**Issue by mapshen** [splitgraph/splitgraph#416]
As per [1], the correct connection string should be

> 'snowflake://<user_login_name>:<password>@<account_name>/<database_name>/<schema_name>?warehouse=<warehouse_name>&role=<role_name>'

but what are constructing is like

```
snowflake://username:password@abcdef.eu-west-1.aws/SOME_DB/TPCH_SF100warehouse=my_warehouse&role=role"
```
where `?` is missing [3].

[1] https://github.com/splitgraph/snowflake-sqlalchemy#connection-parameters
[2] https://github.com/splitgraph/splitgraph/pull/404/files#diff-242b1fb93665dd39dccadee94a3a5fb7310815248452b56a640269eaa49dcfd8R22-R24
[3] https://github.com/splitgraph/splitgraph/pull/404/files#diff-1ded16c49a8e8d9fbb6e60c55e94a75ad3630e4eb5fe4d2861a6dbd7af310941R126

**Comment by mildbyte** [comment]
Thanks for reporting and for pinpointing the issue! I fixed it in https://github.com/splitgraph/splitgraph/commit/79b8e4a85b1d4263084b2743bdcc42654694f67e

**Comment by mapshen** [comment]
Thanks for the quick fix!

In addition, I tested your example mount command
```
sgr -v DEBUG mount snowflake snowflake_sample_data -o@- <<EOF
{
    "username": "DSHEN@TRADEWEB.COM",
    "password": "Rdontk001",
    "account": "SS25982.us-east-1",
    "database": "SNOWFLAKE_SAMPLE_DATA",
    "schema": "TPCH_SF100"
}
EOF
```
and it seems your are assuming the user has a default warehouse set [1]? I am asking because my execution fails since my user doesn't have a default one:
```
error: Traceback (most recent call last):
error:   File "/home/XXX/python3.7/site-packages/splitgraph/commandline/__init__.py", line 116, in invoke
error:     result = super(click.Group, self).invoke(ctx)
error:   File "/home/XXX/python3.7/site-packages/click/core.py", line 1259, in invoke
error:     return _process_result(sub_ctx.command.invoke(sub_ctx))
error:   File "/home/XXX/python3.7/site-packages/click/core.py", line 1259, in invoke
error:     return _process_result(sub_ctx.command.invoke(sub_ctx))
error:   File "/home/XXX/python3.7/site-packages/click/core.py", line 1066, in invoke
error:     return ctx.invoke(self.callback, **ctx.params)
error:   File "/home/XXX/python3.7/site-packages/click/core.py", line 610, in invoke
error:     return callback(*args, **kwargs)
error:   File "/home/XXX/python3.7/site-packages/splitgraph/commandline/mount.py", line 69, in _callback
error:     mount(schema, mount_handler=handler_name, handler_kwargs=handler_options)
error:   File "/home/XXX/python3.7/site-packages/splitgraph/hooks/mount_handlers.py", line 69, in mount
error:     source.mount(schema=mountpoint, overwrite=overwrite, tables=tables)
error:   File "/home/XXX/python3.7/site-packages/splitgraph/hooks/data_source/fdw.py", line 134, in mount
error:     self._create_foreign_tables(schema, server_id, tables)
error:   File "/home/XXX/python3.7/site-packages/splitgraph/hooks/data_source/fdw.py", line 144, in _create_foreign_tables
error:     _import_foreign_schema(self.engine, schema, remote_schema, server_id, tables)
error:   File "/home/XXX/python3.7/site-packages/splitgraph/hooks/data_source/fdw.py", line 299, in _import_foreign_schema
error:     engine.run_sql(query)
error:   File "/home/XXX/python3.7/site-packages/splitgraph/engine/postgres/engine.py", line 501, in run_sql
error:     cur.execute(statement, _convert_vals(arguments) if arguments else None)
error: psycopg2.errors.InternalError_: Error in python: ProgrammingError
error: DETAIL:  (snowflake.connector.errors.ProgrammingError) 000606 (57P03): No active warehouse selected in the current session.  Select an active warehouse with the 'use warehouse' command.
error: 
error: [SQL: 
error:             SELECT /* sqlalchemy:_get_schema_columns */
error:                    ic.table_name,
error:                    ic.column_name,
error:                    ic.data_type,
error:                    ic.character_maximum_length,
error:                    ic.numeric_precision,
error:                    ic.numeric_scale,
error:                    ic.is_nullable,
error:                    ic.column_default,
error:                    ic.is_identity,
error:                    ic.comment
error:               FROM information_schema.columns ic
error:              WHERE ic.table_schema=%(table_schema)s
error:              ORDER BY ic.ordinal_position]
error: [parameters: {'table_schema': 'TPCH_SF100'}]
error: (Background on this error at: http://sqlalche.me/e/14/f405)
error: 
```

[1]https://github.com/splitgraph/splitgraph/pull/404/files#diff-1ded16c49a8e8d9fbb6e60c55e94a75ad3630e4eb5fe4d2861a6dbd7af310941R49-R57

**Comment by mapshen** [comment]
Thanks for the quick fix!

In addition, I tested your example mount command
```
sgr mount snowflake test_snowflake -o@- <<EOF
{
    "username": "username",
    "password": "password",
    "account": "acc-id.west-europe.azure",
    "database": "SNOWFLAKE_SAMPLE_DATA",
    "schema": "TPCH_SF100"
}
EOF
```
and it seems your are assuming the user has a default warehouse set [1]? I am asking because my execution fails since my user doesn't have a default one:
```
error: Traceback (most recent call last):
error:   File "/home/XXX/python3.7/site-packages/splitgraph/commandline/__init__.py", line 116, in invoke
error:     result = super(click.Group, self).invoke(ctx)
error:   File "/home/XXX/python3.7/site-packages/click/core.py", line 1259, in invoke
error:     return _process_result(sub_ctx.command.invoke(sub_ctx))
error:   File "/home/XXX/python3.7/site-packages/click/core.py", line 1259, in invoke
error:     return _process_result(sub_ctx.command.invoke(sub_ctx))
error:   File "/home/XXX/python3.7/site-packages/click/core.py", line 1066, in invoke
error:     return ctx.invoke(self.callback, **ctx.params)
error:   File "/home/XXX/python3.7/site-packages/click/core.py", line 610, in invoke
error:     return callback(*args, **kwargs)
error:   File "/home/XXX/python3.7/site-packages/splitgraph/commandline/mount.py", line 69, in _callback
error:     mount(schema, mount_handler=handler_name, handler_kwargs=handler_options)
error:   File "/home/XXX/python3.7/site-packages/splitgraph/hooks/mount_handlers.py", line 69, in mount
error:     source.mount(schema=mountpoint, overwrite=overwrite, tables=tables)
error:   File "/home/XXX/python3.7/site-packages/splitgraph/hooks/data_source/fdw.py", line 134, in mount
error:     self._create_foreign_tables(schema, server_id, tables)
error:   File "/home/XXX/python3.7/site-packages/splitgraph/hooks/data_source/fdw.py", line 144, in _create_foreign_tables
error:     _import_foreign_schema(self.engine, schema, remote_schema, server_id, tables)
error:   File "/home/XXX/python3.7/site-packages/splitgraph/hooks/data_source/fdw.py", line 299, in _import_foreign_schema
error:     engine.run_sql(query)
error:   File "/home/XXX/python3.7/site-packages/splitgraph/engine/postgres/engine.py", line 501, in run_sql
error:     cur.execute(statement, _convert_vals(arguments) if arguments else None)
error: psycopg2.errors.InternalError_: Error in python: ProgrammingError
error: DETAIL:  (snowflake.connector.errors.ProgrammingError) 000606 (57P03): No active warehouse selected in the current session.  Select an active warehouse with the 'use warehouse' command.
error: 
error: [SQL: 
error:             SELECT /* sqlalchemy:_get_schema_columns */
error:                    ic.table_name,
error:                    ic.column_name,
error:                    ic.data_type,
error:                    ic.character_maximum_length,
error:                    ic.numeric_precision,
error:                    ic.numeric_scale,
error:                    ic.is_nullable,
error:                    ic.column_default,
error:                    ic.is_identity,
error:                    ic.comment
error:               FROM information_schema.columns ic
error:              WHERE ic.table_schema=%(table_schema)s
error:              ORDER BY ic.ordinal_position]
error: [parameters: {'table_schema': 'TPCH_SF100'}]
error: (Background on this error at: http://sqlalche.me/e/14/f405)
error: 
```

[1]https://github.com/splitgraph/splitgraph/pull/404/files#diff-1ded16c49a8e8d9fbb6e60c55e94a75ad3630e4eb5fe4d2861a6dbd7af310941R49-R57

**Comment by mildbyte** [comment]
Yeah, we tested it on a Snowflake trial that spins up a warehouse + some datasets. Is it more common than not to require to specify the warehouse on connection?

**Comment by mapshen** [comment]
I've always done that specifically to avoid using more powerful warehouses and incurring large bills. But it's just my personal preference.
